### ISSUE TITLE
Can JJ.exe be used as a portable application?

### ISSUE THREAD

**Issue by Gavin-Holt** [jj-vcs/jj#203]
Hi,

My life is on a USB stick and I don't have admin rights at work (UK Hospital - Windows 10).

As a hobby programmer I do not want to install git and fight with paths/drive letters or give it 47MB.

JJ as a single file application is very attractive. Many thanks for supplying binaries and please keep the native backend.

I worked through the Tutorial:

1.  Without any installation I have used ```jj git clone``` to create a local copy of my work stored in GitHub.

2.  After editing a few files I can run ```jj st``` which reports the activity and ```jj diff``` to see the alterations.

3.  Closing the commit with ```jj close``` reports a new working copy in green - not blue.

4.  Then ```jj st``` closes the parent (in blue) and reports a new clean working copy (in green).

**How do I push my changes back to GitHub?**

*   I must admit I have not invested in learning git so I may be missing a step.

*   I have tried to run ```jj git push``` but this reports ```Nothing changed```.

*   Making a ~\AppData\Roaming\jj\config.toml file with user name and email did not help.

I am hoping for a really simple clone/pull/push workflow to get me started with GitHub.

Sorry if this is a trivial noob question.

Kind Regards Gavin Holt

**Comment by martinvonz** [comment]
> please keep the native backend.

Yes, that's not going away. I really don't recommend it for anything other than experiments at this point, though. It should work fine for small projects, but if you want a format that's going to be unchanged next year, you should use the git backend.

> How do I push my changes back to GitHub?

Git requires a branch, and the `jj git push` command doesn't currently have a way of creating that branch on the fly. Instead, you'll have to do `jj branch <branch name> -r <commit where it should go, typically "@-" for the parent commit>`. It's possible that `<branch name>` is `main` or `master` in your case, if this is your own repo with a single branch

> I must admit I have not invested in learning git so I may be missing a step.

Interesting. What source control system have you used so far? I thought everyone used Git these days.
