### ISSUE TITLE
failed rebase in colocated git repo: Internal error: Failed to check out commit  - Failed to open, file exists

### ISSUE THREAD

**Issue by alefminus** [jj-vcs/jj#3391]
## Description

Rebasing based on a git repository with submodules causes an internal error.

## Steps to Reproduce the Problem

1. git clone git@github.com:greenvibe-io/renode.git
2. cd renode
3. git remote add upstream  https://github.com/renode/renode.git
4. git fetch upstream
5. git checkout cc1352r2
6. jj git init --git-repo .
7. jj rebase -d HEAD@git -d remotes/upstream/master

Showing failed output for last command only, the full output is at the end of the bug report.

## Expected Behavior

Successful rebase with conflicts (expected).

## Actual Behavior

Rebased 1 commits
ignoring git submodule at "lib/ELFSharp"
ignoring git submodule at "lib/options-parser"
Internal error: Failed to check out commit 86b22c73a15dfb544e257f3919a5b142ec8b3fc5
Caused by:
1: Failed to open file /home/alon/src/jjbug/renode/src/Infrastructure for writing
2: File exists (os error 17)

## Specifications

- Platform: Fedora 39
- Version: 0.15.1

## Additional information

Full output from the reproduction commands.

At this time my renode fork is at commit 2759d45795051c2a84234a4444f155ea0e0d0ca7
Upstream renode repo is at commit 09ac89cb420748a897d2a421c90e9ac07027a7c0

git clone git@github.com:greenvibe-io/renode.git
cd renode
git remote add upstream  https://github.com/renode/renode.git
git fetch upstream
git checkout cc1352r2
jj git init --git-repo .
jj rebase -d HEAD@git -d remotes/upstream/master
Cloning into 'renode'...
remote: Enumerating objects: 18135, done.
remote: Counting objects: 100% (3486/3486), done.
remote: Compressing objects: 100% (1052/1052), done.
remote: Total 18135 (delta 2645), reused 3016 (delta 2427), pack-reused 14649
Receiving objects: 100% (18135/18135), 3.34 MiB | 3.12 MiB/s, done.
Resolving deltas: 100% (10459/10459), done.
remote: Enumerating objects: 2298, done.
remote: Counting objects: 100% (1597/1597), done.
remote: Compressing objects: 100% (524/524), done.
remote: Total 2298 (delta 1137), reused 1486 (delta 1070), pack-reused 701
Receiving objects: 100% (2298/2298), 9.56 MiB | 6.90 MiB/s, done.
Resolving deltas: 100% (1276/1276), completed with 303 local objects.
From https://github.com/renode/renode
 * [new branch]        10872-block_completed_hook      -> upstream/10872-block_completed_hook
 * [new branch]        10872-block_completed_hook-cleanup -> upstream/10872-block_completed_hook-cleanup
 * [new branch]        12053-fix_delayed_actions       -> upstream/12053-fix_delayed_actions
 * [new branch]        14721-cc1200-public             -> upstream/14721-cc1200-public
 * [new branch]        15737-gdb_stepping_issues       -> upstream/15737-gdb_stepping_issues
 * [new branch]        16176--valenty_eptri            -> upstream/16176--valenty_eptri
 * [new branch]        16239_conda_pkg                 -> upstream/16239_conda_pkg
 * [new branch]        18771-spisdcardboot_litex       -> upstream/18771-spisdcardboot_litex
 * [new branch]        18792-realign_memory            -> upstream/18792-realign_memory
 * [new branch]        19800-fix_compilation_on_debian -> upstream/19800-fix_compilation_on_debian
 * [new branch]        19850-litex_i2s                 -> upstream/19850-litex_i2s
 * [new branch]        21322-litesdcard_dma            -> upstream/21322-litesdcard_dma
 * [new branch]        21408-litex_spiflash_quad       -> upstream/21408-litex_spiflash_quad
 * [new branch]        26999-rust_uart                 -> upstream/26999-rust_uart
 * [new branch]        28449-create_spi_connector      -> upstream/28449-create_spi_connector
 * [new branch]        30105-emulation_mode            -> upstream/30105-emulation_mode
 * [new branch]        30303-execution_tracing         -> upstream/30303-execution_tracing
 * [new branch]        32516_external_mmu              -> upstream/32516_external_mmu
 * [new branch]        33756-subobject_logging         -> upstream/33756-subobject_logging
 * [new branch]        33847-tracking_registers        -> upstream/33847-tracking_registers
 * [new branch]        33997-watchpoint_virtual        -> upstream/33997-watchpoint_virtual
 * [new branch]        36284-vcpu                      -> upstream/36284-vcpu
 * [new branch]        37446-mpw_testing               -> upstream/37446-mpw_testing
 * [new branch]        38070-fix-axilite-reset         -> upstream/38070-fix-axilite-reset
 * [new branch]        38171-OpenTitan_I2C_target_mode -> upstream/38171-OpenTitan_I2C_target_mode
 * [new branch]        38199-axilite-initiator         -> upstream/38199-axilite-initiator
 * [new branch]        38527-opentitan_otbn            -> upstream/38527-opentitan_otbn
 * [new branch]        38757-variable_verilator_width  -> upstream/38757-variable_verilator_width
 * [new branch]        39836-quectel_networking_support -> upstream/39836-quectel_networking_support
 * [new branch]        40237-caches_invalidation       -> upstream/40237-caches_invalidation
 * [new branch]        41222-opentitan_spi_device      -> upstream/41222-opentitan_spi_device
 * [new branch]        41410-spi_multiplexer           -> upstream/41410-spi_multiplexer
 * [new branch]        43328-open_titan_bump           -> upstream/43328-open_titan_bump
 * [new branch]        44783-rebase_axilite_support    -> upstream/44783-rebase_axilite_support
 * [new branch]        45408-improve_CI                -> upstream/45408-improve_CI
 * [new branch]        45408-rename_variables_for_verilator_peripherals -> upstream/45408-rename_variables_for_verilator_peripherals
 * [new branch]        45839-skip_wait_if_blocked      -> upstream/45839-skip_wait_if_blocked
 * [new branch]        46376-test_verilated_samples    -> upstream/46376-test_verilated_samples
 * [new branch]        46406-fix_cpu_ibex_testing      -> upstream/46406-fix_cpu_ibex_testing
 * [new branch]        49711-riscv_zfh-package_1       -> upstream/49711-riscv_zfh-package_1
 * [new branch]        49712-riscv_zfh-package_0       -> upstream/49712-riscv_zfh-package_0
 * [new branch]        49897-lis2dw12_resd_rel_time    -> upstream/49897-lis2dw12_resd_rel_time
 * [new branch]        50040-fix_apb3                  -> upstream/50040-fix_apb3
 * [new branch]        50399-fix_verilated_deadlock    -> upstream/50399-fix_verilated_deadlock
 * [new branch]        52362-dpi_ahb                   -> upstream/52362-dpi_ahb
 * [new branch]        53362-fix_serialization_breakpoints -> upstream/53362-fix_serialization_breakpoints
 * [new branch]        Linux_LiteX_VexRiscv            -> upstream/Linux_LiteX_VexRiscv
 * [new branch]        WIP/15677_nmi                   -> upstream/WIP/15677_nmi
 * [new branch]        WIP/19267_address_translation   -> upstream/WIP/19267_address_translation
 * [new branch]        aj-fix-licenses-followup        -> upstream/aj-fix-licenses-followup
 * [new branch]        armv7r-add-configuration-signals -> upstream/armv7r-add-configuration-signals
 * [new branch]        axilite-fixes                   -> upstream/axilite-fixes
 * [new branch]        dotnet_support                  -> upstream/dotnet_support
 * [new branch]        energy-consumption-estimation   -> upstream/energy-consumption-estimation
 * [new branch]        gcov_support                    -> upstream/gcov_support
 * [new branch]        hardening-files_access-and-python -> upstream/hardening-files_access-and-python
 * [new branch]        interop-debug                   -> upstream/interop-debug
 * [new branch]        less-verbose-issues             -> upstream/less-verbose-issues
 * [new branch]        litesdcard_dma                  -> upstream/litesdcard_dma
 * [new branch]        master                          -> upstream/master
 * [new branch]        new_terminal_tester             -> upstream/new_terminal_tester
 * [new branch]        relaxed_conda_requirements      -> upstream/relaxed_conda_requirements
 * [new branch]        renode_verilator_integration    -> upstream/renode_verilator_integration
 * [new branch]        stm32_graphics_improvement_rebased -> upstream/stm32_graphics_improvement_rebased
 * [new branch]        stm32f0--dma-adc                -> upstream/stm32f0--dma-adc
 * [new branch]        tun_tap_on_windows              -> upstream/tun_tap_on_windows
 * [new branch]        vexriscv                        -> upstream/vexriscv
 * [new tag]           v1.1                            -> v1.1
 * [new tag]           v1.10.0                         -> v1.10.0
 * [new tag]           v1.10.1                         -> v1.10.1
 * [new tag]           v1.11.0                         -> v1.11.0
 * [new tag]           v1.12.0                         -> v1.12.0
 * [new tag]           v1.13.0                         -> v1.13.0
 * [new tag]           v1.13.1                         -> v1.13.1
 * [new tag]           v1.13.2                         -> v1.13.2
 * [new tag]           v1.13.3                         -> v1.13.3
 * [new tag]           v1.14.0                         -> v1.14.0
 * [new tag]           v1.2                            -> v1.2
 * [new tag]           v1.3                            -> v1.3
 * [new tag]           v1.4                            -> v1.4
 * [new tag]           v1.4.1                          -> v1.4.1
 * [new tag]           v1.5                            -> v1.5
 * [new tag]           v1.6                            -> v1.6
 * [new tag]           v1.6.1                          -> v1.6.1
 * [new tag]           v1.6.2                          -> v1.6.2
 * [new tag]           v1.7                            -> v1.7
 * [new tag]           v1.7.1                          -> v1.7.1
 * [new tag]           v1.8                            -> v1.8
 * [new tag]           v1.8.1                          -> v1.8.1
 * [new tag]           v1.8.2                          -> v1.8.2
 * [new tag]           v1.8.2_with_new_terminal_tester -> v1.8.2_with_new_terminal_tester
 * [new tag]           v1.9.0                          -> v1.9.0
 * [new tag]           v1.15.0                         -> v1.15.0
branch 'cc1352r2' set up to track 'origin/cc1352r2'.
Switched to a new branch 'cc1352r2'
Done importing changes from the underlying Git repo.
ignoring git submodule at "lib/AntShell"
ignoring git submodule at "lib/BigGustave"
ignoring git submodule at "lib/CxxDemangler"
ignoring git submodule at "lib/ELFSharp"
ignoring git submodule at "lib/FdtSharp"
ignoring git submodule at "lib/InpliTftpServer"
ignoring git submodule at "lib/Migrant"
ignoring git submodule at "lib/Packet.Net"
ignoring git submodule at "lib/bc-csharp"
ignoring git submodule at "lib/cctask"
ignoring git submodule at "lib/options-parser"
ignoring git submodule at "lib/termsharp"
ignoring git submodule at "src/Infrastructure"
The following remote branches aren't associated with the existing local branches:
  cc1352r2@origin
  master@origin
  master@upstream
Hint: Run `jj branch track cc1352r2@origin master@origin master@upstream` to keep local branches updated on future pulls.
Initialized repo in "."
(and then the output pasted above under "Actual Behavior")

**Comment by yuja** [comment]
> ignoring git submodule at "src/Infrastructure"

jj doesn't properly support Git submodules. Maybe that's why. #494
