### ISSUE TITLE
FR: Automatically `jj workspace update-stale`

### ISSUE THREAD

**Issue by torquestomp** [jj-vcs/jj#3820]
**Is your feature request related to a problem? Please describe.**
When working with a repo that has multiple working copies, it is common to sync/fetch/rebase in one wc before switching to another.  This often requires running `jj workspace update-stale` to update the working copy, but this is generally busy work and usually does not materially impact the thing being worked on in the other wc.

**Describe the solution you'd like**
A new config option, e.g. "ui.always-update-stale" which causes jj to automatically run `jj workspace update-stale` for me whenever it's necessary, printing a status message about it and proceeding with the original command rather than halting execution, making me run `jj workspace update-stale` manually and then re-running the original command.

**Comment by PhilipMetzger** [comment]
done as of 49890fa
