### ISSUE TITLE
Windows: UNC paths do not work well with other programs

### ISSUE THREAD

**Issue by mlcui-corp** [jj-vcs/jj#3986]
This is acknowledged in [the documentation for `std::fs::canonicalize`](https://doc.rust-lang.org/std/fs/fn.canonicalize.html#platform-specific-behavior):

> On Windows, this converts the path to use [extended length path syntax](https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file), which allows your program to use longer path names, but means you can only join backslash-delimited paths to it, and **it may be incompatible with other applications** (if passed to the application on the command-line, or written to a file another application may read).

and in the [documentation for `dunce`](https://docs.rs/dunce/latest/dunce/), a Rust crate:

> [UNC paths] are more robust and with fewer gotchas [compared to regular/legacy paths], but are rarely supported by Windows programs. Even Microsoft’s own!

This is causing issues - for example, setting IntelliJ IDEA as a **diff** editor does not work, but setting it as a **merge** editor does work - probably due to the inconsistent `canonicalize`-ation of the paths.

I think the most straightforward solution would be to use the aforementioned crate `dunce`, which could strip the prefix (if possible) before calling external tools.

**Comment by yuja** [comment]
This should be addressed by c256ad8a0aa43a1acb8a5e4c69ed2baf4f8976d3.
