### ISSUE TITLE
FR: Reconstruct a specific change_id

### ISSUE THREAD

**Issue by tim-janik** [jj-vcs/jj#5116]
**Is your feature request related to a problem? Please describe.**

Currently, jj has no command that supports creating a new commit with a specific change ID or changing an existing change ID. This limitation makes it close to impossible to recreate a specific change ID, that has been learned from another repository through e.g. [jj-am.sh](https://github.com/tim-janik/jj-fzf/blob/trunk/contrib/jj-am.sh), which can be used to mirror commits across different repositories.
(Setting JJ_RANDOMNESS_SEED after an inverse chacha20 round could theoretically force a specific change ID, but this is not a practical solution.)

Additionally, there are divergent change_id cases, where *keeping* a commit under a new (different) change_id would be desirable, in such cases it would be nice to simply regenerate a new change_id with a single (simple) command for such a commit.

**Describe the solution you'd like**
```sh
jj describe --help

  --new-change-id <CHANGE_ID>       Assign a specific change ID or prefix to an existing revision.
  --random-change-id                Assign a newly generated random change ID to an existing revision.
```

**Implementation Notes**

* The --new-change-id  option should validate, that the provided change ID follows the expected format ^[k-z]*$
* Overlong change_ids should be rejected.
* Shortened change_ids (prefix specification) should be accepted, the missing tail should be randomized.
* A --random-change-id option needs to be added, unless the above suggested support for prefix change_ids is implemented. In that case `jj describe --new-change-id=''` could be used to generate a new, fully randomized change_id.
* The --new-change-id option should permit creating divergent change_ids, that way repos with divergent change_ids can be mirrored (with e.g. format-patch + jj-am.sh).

**Describe alternatives you've considered**

Not support change_id transfers between repos, we have that now and experience its downsides daily.

**Additional context**

Note that this feature needs implementation anyways when support for a custom header like `jj_change_id` in Git commits is implemented. Adjusting divergent change_id cases and the jj-am.sh use case are good reasons to also expose this functionality through the CLI.

Related Discord discussion: 
[Martin von Zweigbergk: perhaps it could be an option to jj describe](https://discord.com/channels/968932220549103686/1317220060548436110/1317247231912579163)

**Comment by yuja** [comment]
I think this is a dup of https://github.com/martinvonz/jj/issues/4451. Can you copy your idea to #4451 issue and close this?

FWIW, if we add a flag to `jj describe`, I would call `--random-change-id` as `--reset-change-id` or `--renew-change-id`.

**Comment by tim-janik** [comment]
[Done](https://github.com/jj-vcs/jj/issues/4451#issuecomment-2552728553).
And thanks for your suggestion, it is integrated into my proposal.
