### ISSUE TITLE
FR: Add jj absorb option --skip-emptied

### ISSUE THREAD

**Issue by tim-janik** [jj-vcs/jj#5141]
**Is your feature request related to a problem? Please describe.**

In the last few weeks I have gotten used to employing `jj absorb` in my workflow.
Since it's easy in jj-fzf to navigate to a particular commit and absorb it with a single key press (Alt+O), I have started to use it on commits other than the working copy. It can be a natural extension to squash-into-parent, just way more clever. And just like with squash, it'd be helpful to not end up with a useless empty commit in the middle of the history. 

**Describe the solution you'd like**
Ideally, there would be a `jj absorb --skip-emptied` option, similar to `jj rebase --skip-emptied` (or the `jj squash` default), that discards the absorbed commit if it turns out to be empty and is not the working copy.
Discarding the working copy would be pointless (squash also doesn't do this, or at least creates a new empty commit), so the new option could be ignored in that case.

**Describe alternatives you've considered**
Less convenient, but basically the empty commit can be identified after the fact and manually abandoned after close inspection to verify it actually is empty.

**Additional context**
IIUC, the outcome of [git-absorb](https://github.com/tummychow/git-absorb?tab=readme-ov-file#usage) also mimics squash like behavior, if that is at all comparable...

**Comment by yuja** [comment]
I think `jj absorb` is closer to `squash` than `rebase`, so it might be better to make it abandon discardable source commit by default, and add `-k`/`--keep-emptied` if needed. One difference is that `absorb` never "squashes" commit description.

FWIW, if we add rebase-like `--skip-emptied`, it'll also mean emptied destination commits are abandoned.

**Comment by tim-janik** [comment]
> I think `jj absorb` is closer to `squash` than `rebase`, so it might be better to make it abandon discardable source commit by default, and add `-k`/`--keep-emptied` if needed. One difference is that `absorb` never "squashes" commit description.

I agree, it feels very *squash* like.
