### ISSUE TITLE
`jj commit -i` fails to remove file

### ISSUE THREAD

**Issue by doudou** [jj-vcs/jj#5150]
## Description

I have a working copy with two files removed. If I try to create a commit with the removal only using `commit -i`, the created commit is empty.

## Steps to Reproduce the Problem

![image](https://github.com/user-attachments/assets/16713c6c-e8ab-4b7d-befc-92a0bca6747d)

In the `jj commit -i` window, I selected the `test/a` changes. I did add some content to both a and b files using vi (random text)

Doing a  `jj commit test/a` works as expected

## Expected Behavior

The commit created using `commit -i` should contain the file removal.

## Actual Behavior

The commit created using `commit -i` is empty (as indicated)

## Specifications

- Platform: Ubuntu 20.04
- Version: jj 0.24.0

**Comment by mrnossiom** [comment]
I was able to reproduce without a folder.


Commands extracted from the image (removed the folder step) :

```sh
# in a empty temporary folder
git init
jj git init --colocate
hx a
hx b
jj commit -m "first"
rm a
jj st
jj commit -i -m "second"
ls test
```

**Comment by martinvonz** [comment]
Sounds like #3702

**Comment by martinvonz** [comment]
That's our most upvoted bug, btw (but there are more-updated FRs). If anyone wants to help with that, it would be greatly appreciated.
