### ISSUE TITLE
jj with https for a private, hosted github

### ISSUE THREAD

**Issue by jeanbza** [jj-vcs/jj#5166]
## Description

Hello, I've been playing with `jj` after missing `hg` (😢 ). It's great so far, well done!

The issue that I'm running into is that `jj` seems to be unable to interoperate with a private hosted GitHub that does not allow SSH keys. Is this a known issue? Is there a workaround? I'd really love to use `jj` as my primary git driver.

## Steps to Reproduce the Problem

1. Have a private, hosted GitHub
1. Try to clone a repo with `jj` and https. Ex:

```
jbarkhuysen at Jeans-MacBook-Pro in ~/workspace
$ jj git clone https://git.netflix.net/corp/stratum-envoy.git
Fetching into new repo in "/Users/jbarkhuysen/workspace/stratum-envoy"
Error: unexpected http status code: 404; class=Http (34)
```

## Expected Behavior

Works.

## Actual Behavior

404

## Specifications

- Platform: Mac
- Version: `0.24.0`

----------------

I am sort of able to get around this by doing `git clone ...` and then `git init --colocate`, which happily lets me do `jj`-ish things until I need to push:

```
jbarkhuysen at Jeans-MacBook-Pro in ~/workspace/stratum-envoy on (HEAD detached at 8c8e670)
$ jj git push -c @-
Creating bookmark push-tykvvzmrzlll for revision tykvvzmrzlll
Changes to push to origin:
  Add bookmark push-tykvvzmrzlll to 8c8e670e9676
Error: unexpected http status code: 404; class=Http (34)
```

**Comment by jeanbza** [comment]
Ah, this is https://github.com/jj-vcs/jj/issues/469. Sorry!

**Comment by arxanas** [comment]
@jeanbza see also https://github.com/jj-vcs/jj/issues/4979 lol
