### ISSUE TITLE
jj won't install

### ISSUE THREAD

**Issue by knowingpark** [jj-vcs/jj#5175]
## Steps to Reproduce the Problem

1. sudo cargo install --git https://github.com/martinvonz/jj.git --locked --bin jj jj-cli or
1. cargo install --locked --bin jj jj-cli
1.

## Expected Behavior
JJ installs

## Specifications

- Platform: Linux mint Debian edition (v6 Faye)  
- Version: Linux Kernel 6.1.0-28-amd64
- System:
  Kernel: 6.1.0-28-amd64 arch: x86_64 bits: 64 compiler: gcc v: 12.2.0 Desktop: Cinnamon v: 6.2.9
    tk: GTK v: 3.24.38 wm: muffin vt: 7 dm: LightDM v: 1.26.0 Distro: LMDE 6 Faye
    base: Debian 12.1 bookworm
Machine:
  Type: Desktop System: LENOVO product: 10ACS0GC00 v: ThinkCentre M93z serial: <superuser required>
  Mobo: LENOVO model: N/A v: 0B98405 STD serial: <superuser required> BIOS: LENOVO v: FEKT85AUS
    date: 07/25/2014

**Comment by yuja** [comment]
Maybe it's a bug of cargo? https://github.com/rust-lang/cargo/issues/10788

Can you try more recent version of rustc and cargo if you're using the version installed by apt?

**Comment by knowingpark** [comment]
I reinstall rust/cargo via curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
(as suggested by https://itsfoss.com/install-rust-cargo-ubuntu-linux/)
Then ran the jj install again and it worked.
Thanks
