### ISSUE TITLE
README still says there is no equivalent to git blame

### ISSUE THREAD

**Issue by keanemind** [jj-vcs/jj#5191]
## Description

The README in this repo still says
> The tool is fairly feature-complete, but some important features like (the equivalent of) git blame are not yet supported.

But as of https://github.com/jj-vcs/jj/pull/4176 / https://github.com/jj-vcs/jj/commit/470275b0d0f258c11d2393e8a55d92f604237078 there's `jj annotate`, which the docs even compare with `git blame`  as of https://github.com/jj-vcs/jj/pull/4918. 

Perhaps it could be changed to
> The tool is fairly feature-complete, but some important features like support for Git submodules are not yet completed.

**Comment by PhilipMetzger** [comment]
done as of [7402362](https://github.com/jj-vcs/jj/commit/7402362c80a6af1a609e9fb05009e624fb566252)
