### ISSUE TITLE
EDITOR set to executable script results in exec format error

### ISSUE THREAD

**Issue by neutralinsomniac** [jj-vcs/jj#5200]
## Description

My editor is actually an executable script that runs my actual editor bin with some custom env vars set. Git and other tools seem to work fine with this setup, but jj throws an exec format error when running any commands that would spawn my editor.

## Steps to Reproduce the Problem

1. Set environment variable EDITOR to point to an executable script.
1. Run a jj command that attempts to launch an editor, like `jj desc`
1. Observe error:
```
[jeremy@xps13:~/flake]$ jj desc
Error: Failed to run editor 'hx'
Caused by: Exec format error (os error 8)
```

## Expected Behavior
Editor launches as normal.

## Actual Behavior
jj errors.

## Specifications

- Platform: NixOS Linux x64
- Version: 0.24.0

**Comment by samueltardieu** [comment]
With master, on NixOS as well:

```bash
$ cat /tmp/t.sh
#! /bin/sh

vim "$@"
$ chmod 755 /tmp/t.sh
$ EDITOR=/tmp/t.sh jj desc
[edit prompt as expected]
```

What exactly did you use as your `$EDITOR`, which which mode? You most likely forgot to include a proper shebang (`#!`) first line to set the interpreter. The other programs you mention most likely use `sh -c $EDITOR` which works even with an impropre shebang line.

**Comment by neutralinsomniac** [comment]
You got it. I was using `pkgs.writeScriptBin` and didn't include the shebang. I think I just assumed nix would've done some magic for me there :sweat_smile:

Thanks!
